config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "inventory_levels#index"
  
  resources :inventory_levels
  resources :warehouses
  resources :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inventory_level.rb
class InventoryLevel < ApplicationRecord
    belongs_to :item
    belongs_to :warehouse
    
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :inventory_levels

    def total_value
        if self.inventory_levels.count > 0
            self.inventory_level.available * self.cost
        end
    end

end

app/models/warehouse.rb
class Warehouse < ApplicationRecord
    has_many :inventory_levels
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/inventory_levels_controller.rb
class InventoryLevelsController < ApplicationController
  skip_before_action :verify_authenticity_token 
  before_action :set_inventory_level, only: %i[ show edit update destroy ]

  # GET /inventory_levels or /inventory_levels.json
  def index
    @inventory_levels = InventoryLevel.all
  end

  # GET /inventory_levels/1 or /inventory_levels/1.json
  def show
  end

  # GET /inventory_levels/new
  def new
    @inventory_level = InventoryLevel.new
  end

  # GET /inventory_levels/1/edit
  def edit
    
  end

  # POST /inventory_levels or /inventory_levels.json
  def create
    @inventory_level = InventoryLevel.new(inventory_level_params)

    respond_to do |format|
      if @inventory_level.save
        format.html { redirect_to inventory_level_url(@inventory_level), notice: "Inventory level was successfully created." }
        format.json { render :show, status: :created, location: @inventory_level }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @inventory_level.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventory_levels/1 or /inventory_levels/1.json
  def update
    respond_to do |format|
      if @inventory_level.update(inventory_level_params)
        format.html { redirect_to inventory_level_url(@inventory_level), notice: "Inventory level was successfully updated." }
        format.json { render :show, status: :ok, location: @inventory_level }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @inventory_level.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventory_levels/1 or /inventory_levels/1.json
  def destroy
    @inventory_level.destroy

    respond_to do |format|
      format.html { redirect_to inventory_levels_url, notice: "Inventory level was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory_level
      @inventory_level = InventoryLevel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def inventory_level_params
      params.require(:inventory_level).permit(:available,:item_id,:warehouse_id)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
 skip_before_action :verify_authenticity_token 
  before_action :set_item, only: %i[ show edit update destroy]

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :cost)
    end
end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_warehouse, only: %i[ show edit update destroy ]

  # GET /warehouses or /warehouses.json
  def index
    @warehouses = Warehouse.all
  end

  # GET /warehouses/1 or /warehouses/1.json
  def show
  end

  # GET /warehouses/new
  def new
    @warehouse = Warehouse.new
  end

  # GET /warehouses/1/edit
  def edit
  end

  # POST /warehouses or /warehouses.json
  def create
    @warehouse = Warehouse.new(warehouse_params)

    respond_to do |format|
      if @warehouse.save
        format.html { redirect_to warehouse_url(@warehouse), notice: "Warehouse was successfully created." }
        format.json { render :show, status: :created, location: @warehouse }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @warehouse.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /warehouses/1 or /warehouses/1.json
  def update
    respond_to do |format|
      if @warehouse.update(warehouse_params)
        format.html { redirect_to warehouse_url(@warehouse), notice: "Warehouse was successfully updated." }
        format.json { render :show, status: :ok, location: @warehouse }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @warehouse.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /warehouses/1 or /warehouses/1.json
  def destroy
    @warehouse.destroy

    respond_to do |format|
      format.html { redirect_to warehouses_url, notice: "Warehouse was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_warehouse
      @warehouse = Warehouse.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def warehouse_params
      params.require(:warehouse).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/inventory_levels/_create.html.erb
<%= form_with(model: inventory_level) do |form| %>
  <% if inventory_level.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inventory_level.errors.count, "error") %> prohibited this inventory_level from being saved:</h2>

      <ul>
        <% inventory_level.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :item_id %>
    <%= form.number_field :item_id %>
  </div>
  
  <div class="field">
    <%= form.label :warehouse_id %>
    <%= form.number_field :warehouse_id %>
  </div>

  <div class="field">
    <%= form.label :available %>
    <%= form.number_field :available %>
  </div>




  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/inventory_levels/_form.html.erb
<%= form_with(model: inventory_level) do |form| %>
  <% if inventory_level.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inventory_level.errors.count, "error") %> prohibited this inventory_level from being saved:</h2>

      <ul>
        <% inventory_level.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <strong>Item:</strong>
    <%= @inventory_level.item.name %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= @inventory_level.warehouse.name %>
  </p>
  
  <p>
    <strong>Location ID:</strong>
    <%= @inventory_level.warehouse_id %>
  </p>

<h3> Change Qty Available or Location </h3>
  <div class="field">
    <%= form.label :available %>
    <%= form.number_field :available %>
  </div>

  <div class="field">
    <%= form.label 'Location ID' %>
    <%= form.number_field :warehouse_id %>
  </div>




  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/inventory_levels/edit.html.erb
<h1>Editing Inventory</h1>

<h3> Current Item and Location </h3>

<%= render 'form', inventory_level: @inventory_level %>

<%= link_to 'Show', @inventory_level %> |
<%= link_to 'Back', inventory_levels_path %>

app/views/inventory_levels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inventory</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Cost/Unit</th>
      <th>Available</th>
      <th>Warehouse</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @inventory_levels.each do |inventory_level| %>
      <tr>
        <td><%= inventory_level.item.name %></td>
        <td><%= number_to_currency(inventory_level.item.cost, :unit => "$")%></td>
        <td><%= inventory_level.available %></td>
        <td><%= inventory_level.warehouse.name %>></td>
        <td><%= link_to 'Show', inventory_level %></td>
        <td><%= link_to 'Edit', edit_inventory_level_path(inventory_level) %></td>
        <td><%= link_to 'Destroy', inventory_level, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Item', new_item_path %>
<br>
<%= link_to 'New Warehouse', new_warehouse_path %>

app/views/inventory_levels/new.html.erb
<h1>New Inventory Level</h1>

<%= render 'create', inventory_level: @inventory_level %>

<%= link_to 'Back', inventory_levels_path %>

app/views/inventory_levels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Qty Available:</strong>
  <%= @inventory_level.available %>
</p>

<p>
  <strong>Item:</strong>
  <%= @inventory_level.item.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @inventory_level.warehouse.name %>
</p>

<%= link_to 'Edit', edit_inventory_level_path(@inventory_level) %> |
<%= link_to 'Back', inventory_levels_path %>

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :cost %>
    <%= form.text_field :cost %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inventory</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Quantity</th>
      <th>Cost</th>
      <th>Total</th>
      <th>Location</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.quantity %></td>
        <td><%= number_to_currency(item.cost, :unit => "$")%></td>
        <td><%= number_to_currency(item.total_value, :unit=> "$") %>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item_path(item, type: :normal ), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create New Item', new_item_path %>
<br>




           

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @item.cost %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/warehouses/_form.html.erb
<%= form_with(model: warehouse) do |form| %>
  <% if warehouse.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(warehouse.errors.count, "error") %> prohibited this warehouse from being saved:</h2>

      <ul>
        <% warehouse.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/warehouses/edit.html.erb
<h1>Editing Warehouse</h1>

<%= render 'form', warehouse: @warehouse %>

<%= link_to 'Show', @warehouse %> |
<%= link_to 'Back', warehouses_path %>

app/views/warehouses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Warehouses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @warehouses.each do |warehouse| %>
      <tr>
        <td><%= warehouse.name %></td>
        <td><%= link_to 'Show', warehouse %></td>
        <td><%= link_to 'Edit', edit_warehouse_path(warehouse) %></td>
        <td><%= link_to 'Destroy', warehouse, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Warehouse', new_warehouse_path %>
<br>
<%= link_to 'Inventory List', inventory_levels_path%>

app/views/warehouses/new.html.erb
<h1>New Warehouse</h1>

<%= render 'form', warehouse: @warehouse %>

<%= link_to 'Back', warehouses_path %>

app/views/warehouses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @warehouse.name %>
</p>

<%= link_to 'Edit', edit_warehouse_path(@warehouse) %> |
<%= link_to 'Back', warehouses_path %>